"""Created many to many relationship between users and chapters with an auxillary model called quiz that also holds the score for each chapter.

Revision ID: 76f87671f871
Revises: 
Create Date: 2025-03-28 17:44:12.887263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f87671f871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('student_id', 'users', ['student_id'], ['id'])
        batch_op.create_foreign_key('chapter_id', 'chapters', ['chapter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('score')
        batch_op.drop_column('chapter_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
