"""questions model added

Revision ID: 82498235bd4d
Revises: 1a2b5d5cca1a
Create Date: 2025-03-27 16:30:33.253514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82498235bd4d'
down_revision = '1a2b5d5cca1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ques', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('option1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('option2', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('option3', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('option4', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('correct', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('correct')
        batch_op.drop_column('option4')
        batch_op.drop_column('option3')
        batch_op.drop_column('option2')
        batch_op.drop_column('option1')
        batch_op.drop_column('ques')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
