"""some changes

Revision ID: 9e8c568ccc5b
Revises: 82498235bd4d
Create Date: 2025-03-27 21:55:53.302355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8c568ccc5b'
down_revision = '82498235bd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chap_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'chapters', ['chap_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chap_id')

    # ### end Alembic commands ###
